### ISSUE TITLE
Constant WP_POST_REVISIONS already defined

### ISSUE THREAD

**Issue by indietravel** [tillkruss/wp-cli-kraken#1]
Non-fatal php warning is being created:

`$ wp media krake --dry-run`
`PHP Notice:  Constant WP_POST_REVISIONS already defined in phar:///usr/local/wp-cli/wp-cli-0.19.0.phar/php/wp-cli.php(23) : eval()'d code on line 50`

Let me know if I can supply further information for troubleshooting. Not sure what, if anything, is needed.

**Comment by tillkruss** [comment]
This command isn't using the `WP_POST_REVISIONS` constant, I'd assume you're setting it twice in your installation or once, but too late.

**Comment by indietravel** [comment]
Interesting. I opened this since the warning was only showing up with this cli command. I’ll debug further, and update here if I find anything useful.
