### ISSUE TITLE
Feature Request: metadata and image resizing options in wp-cli.yml

### ISSUE THREAD

**Issue by jonhendershot** [tillkruss/wp-cli-kraken#6]
I have a site with 60,000+ image files on it and I really want to use this tool to work on some automated optimizations, but I don't see any settings for dropping image metadata or image resizing. Both options are pretty important to me so it'd be great to have them!

**Comment by jonhendershot** [comment]
Just realized kraken drops all meta by default - I'm gonna dig in to an image resizing param on my copy :)

**Comment by tillkruss** [comment]
You're welcome to submit a PR anytime. I tend to use imgix for resizing.
